zstyle :plugin:fast-syntax-highlighting theme "custom"
typeset -g FAST_THEME_NAME="custom"
: ${FAST_HIGHLIGHT_STYLES[customdefault]:=grey}
: ${FAST_HIGHLIGHT_STYLES[customunknown-token]:=none}
: ${FAST_HIGHLIGHT_STYLES[customreserved-word]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customalias]:=bold}
: ${FAST_HIGHLIGHT_STYLES[customsuffix-alias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[custombuiltin]:=bold}
: ${FAST_HIGHLIGHT_STYLES[customfunction]:=bold}
: ${FAST_HIGHLIGHT_STYLES[customcommand]:=bold}
: ${FAST_HIGHLIGHT_STYLES[customprecommand]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[customcommandseparator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[customhashed-command]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[custompath]:=fg=magenta,bold}
: ${FAST_HIGHLIGHT_STYLES[custompath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[customglobbing]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[customhistory-expansion]:=fg=blue,bold,underline}
: ${FAST_HIGHLIGHT_STYLES[customsingle-hyphen-option]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customdouble-hyphen-option]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customback-quoted-argument]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[customsingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customdouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customdollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customback-or-dollar-double-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customback-dollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[customredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[customcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[customvariable]:=fg=113}
: ${FAST_HIGHLIGHT_STYLES[custommathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[custommathnum]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[custommatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[customassign-array-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[customfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[customfor-loop-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[customfor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customfor-loop-separator]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[customexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[customhere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customhere-string-word]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[customsecondary]:=}
: ${FAST_HIGHLIGHT_STYLES[customcase-input]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[customcase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[customcase-condition]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[customcorrect-subtle]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[customincorrect-subtle]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[customsubtle-bg]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[custompath-to-dir]:=fg=magenta,bold}
: ${FAST_HIGHLIGHT_STYLES[custompaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[custombracket-level-1]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[custombracket-level-2]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[custombracket-level-3]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[customglobal-alias]:=bg=blue}
